import java.util.Scanner;

// An alternative solution to this in question generated by AI.
public class AlternativeCalculator {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        double result = getValidNumber(sc, "Enter first number: ");
        
        while (true) {
            String operator = getValidOperator(sc, "Enter operator (+, -, *, /) or = to calculate: ");
            if (operator.equals("=")) {
                System.out.println("Result: " + result);
                break;
            }
            
            double nextNumber = getValidNumber(sc, "Enter next number: ");
            
            switch (operator) {
                case "+":
                    result += nextNumber;
                    break;
                case "-":
                    result -= nextNumber;
                    break;
                case "*":
                    result *= nextNumber;
                    break;
                case "/":
                    if (nextNumber != 0) {
                        result /= nextNumber;
                    } else {
                        System.out.println("Error: Division by zero. Please enter a different number.");
                        // Optionally, prompt again for a valid next number here
                    }
                    break;
            }
        }
        sc.close();
    }

    private static double getValidNumber(Scanner sc, String prompt) {
        while (true) {
            System.out.print(prompt);
            String input = sc.nextLine();
            try {
                return Double.parseDouble(input);
            } catch (NumberFormatException e) {
                System.out.println("Invalid input. Please enter a number.");
            }
        }
    }

    private static String getValidOperator(Scanner sc, String prompt) {
        while (true) {
            System.out.print(prompt);
            String op = sc.nextLine();
            if (op.equals("+") || op.equals("-") || op.equals("*") || op.equals("/") || op.equals("=")) {
                return op;
            }
            System.out.println("Invalid operator. Please enter +, -, *, / or =.");
        }
    }
}